---
generate-pipeline:
  stage: build
  image: node:20
  script:
    - npx projen install:ci
    - npx ts-node .gitlab-ci.ts
  artifacts:
    paths:
      - generated-config.yml
  tags:
    - gcix

run-pipeline:
  stage: deploy
  needs:
    - generate-pipeline
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-pipeline
    strategy: depend
